DROP DATABASE IF EXISTS roc;

CREATE DATABASE roc;

USE roc;

GRANT SELECT, INSERT, UPDATE, DELETE ON roc.* to 'www'@'localhost' IDENTIFIED BY 'www';

CREATE TABLE urls(
    `id` INT NOT NULL AUTO_INCREMENT,
    `long_url` VARCHAR(2000) NOT NULL DEFAULT '',
    `created_time` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;